server:
  port: 22727

spring:
  application:
    name: aviasales-admin-app
    version: 1.0
  jta:
    atomikos:
      datasource:
        aviasales-admin-xa-ds:
          unique-resource-name: aviasalesAdminXADS
          xa-data-source-class-name: org.postgresql.xa.PGXADataSource
          xa-properties:
            url: ${AVIASALES_ADMIN_APP_JDBC:jdbc:postgresql://158.160.85.230:5432/aviasales-admin}
            user: ${AVIASALES_ADMIN_APP_DB_USER:aviasales}
            password: ${AVIASALES_ADMIN_APP_DB_PASS:aviasales}
          min-pool-size: 5
          max-pool-size: 20
    jpa:
      transaction-type: JTA
      properties:
        hibernate:
          transaction.coordinator_class: jta
          current_session_context_class: jta
  liquibase:
    change-log: classpath:liquibase/changelog.xml
    drop-first: true # удаляет все данные после перезапуска
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

token:
  signing:
    key: ${TOKEN_SIGNING_KEY:53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855}

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE

kafka-topics:
  advertisement-creation-requests: advertisement-creation-requests
